### ISSUE TITLE
Sweet alert on kiosk page no longer displays 

### ISSUE THREAD

**Issue by Volxz** [BealDevelopment/BluePanel#26]
When you did the tumout function it someho broke the kiosk sweet alert @salamander2 . I can revert the page or if you think it is fixable we can do that too.

**Comment by salamander2** [comment]
Fixed in dev branch. 
The problem was calling one function inside another. I've made some other fixes to get the focus working.
The sweetalert will still timeout after 5 seconds. The input box gets focus after 1 second and after 5 seconds. This means that the fastest that barcodes can be scanned in or out is at intervals of 1 second.
